"""New fields to user model

Revision ID: 04957a3d4f58
Revises: 1f72fcda248f
Create Date: 2018-07-30 16:34:22.155462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04957a3d4f58'
down_revision = '1f72fcda248f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
